[[TODO]]
target = "https://www.rfc-editor.org/rfc/rfc9000#section-17.2.5.1"
quote = '''
A client MUST
discard a Retry packet that contains a Source Connection ID field
that is identical to the Destination Connection ID field of its
Initial packet.
'''
tracking-issue = "396"
feature = "Client Retry" 

[[TODO]]
target = "https://www.rfc-editor.org/rfc/rfc9000#section-17.2.5.2"
quote = '''
A client MUST accept and process at most one Retry packet for each
connection attempt.
'''
tracking-issue = "396"
feature = "Client Retry" 

[[TODO]]
target = "https://www.rfc-editor.org/rfc/rfc9000#section-17.2.5.2"
quote = '''
Clients MUST discard Retry packets that have a Retry Integrity Tag
that cannot be validated; see Section 5.8 of [QUIC-TLS].
'''
tracking-issue = "396"
feature = "Client Retry" 

[[TODO]]
target = "https://www.rfc-editor.org/rfc/rfc9000#section-17.2.5.2"
quote = '''
After the client has received and processed an
Initial or Retry packet from the server, it MUST discard any
subsequent Retry packets that it receives.
'''
tracking-issue = "397"
feature = "Client Retry" 
