target = "https://www.rfc-editor.org/rfc/rfc9000#section-2.3"

[[TODO]]
quote = '''
A QUIC implementation SHOULD provide ways in which an application can
indicate the relative priority of streams.
'''
feature = "Stream prioritization"
tracking-issue = "228"
