target = "https://www.rfc-editor.org/rfc/rfc9000#section-5.1.2"

[[TODO]]
quote = '''
Endpoints SHOULD retire connection IDs when
they are no longer actively using either the local or destination
address for which the connection ID was used.
'''
feature = "Peer Connection ID Management"
tracking-issue = "2043"

[[TODO]]
quote = '''
Endpoints SHOULD NOT issue updates of the Retire Prior To field
before receiving RETIRE_CONNECTION_ID frames that retire all
connection IDs indicated by the previous Retire Prior To value.
'''
tracking-issue = "380"

