target = "https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#5.1.1"

[[TODO]]
quote = '''
An endpoint MAY
send connection IDs that temporarily exceed a peer's limit if the
NEW_CONNECTION_ID frame also requires the retirement of any excess,
by including a sufficiently large value in the Retire Prior To field.
'''
feature = "Local Connection ID Management"
tracking-issue = "238"

[[TODO]]
quote = '''
An endpoint SHOULD supply a new connection ID when the peer retires a
connection ID.
'''
feature = "Local Connection ID Management"
tracking-issue = "238"

[[TODO]]
quote = '''
If an endpoint provided fewer connection IDs than the
peer's active_connection_id_limit, it MAY supply a new connection ID
'''
feature = "Local Connection ID Management"
tracking-issue = "238"

[[TODO]]
quote = '''
An
endpoint MAY limit the total number of connection IDs issued for each
connection to avoid the risk of running out of connection IDs; see
Section 10.3.2.
'''
feature = "Local Connection ID Management"
tracking-issue = "238"

[[TODO]]
quote = '''
An endpoint that initiates migration and requires non-zero-length
connection IDs SHOULD ensure that the pool of connection IDs
available to its peer allows the peer to use a new connection ID on
migration, as the peer will be unable to respond if the pool is
exhausted.
'''
feature = "Local Connection ID Management"
tracking-issue = "238"
