target = "https://www.rfc-editor.org/rfc/rfc9002#section-6.3"

# Handling Retry Packets
#
#    A Retry packet causes a client to send another Initial packet,
#    effectively restarting the connection process.  A Retry packet
#    indicates that the Initial packet was received but not processed.  A
#    Retry packet cannot be treated as an acknowledgment because it does
#    not indicate that a packet was processed or specify the packet
#    number.
# 
#    Clients that receive a Retry packet reset congestion control and loss
#    recovery state, including resetting any pending timers.  Other
#    connection state, in particular cryptographic handshake messages, is
#    retained; see Section 17.2.5 of [QUIC-TRANSPORT].
# 
#    The client MAY compute an RTT estimate to the server as the time
#    period from when the first Initial packet was sent to when a Retry or
#    a Version Negotiation packet is received.  The client MAY use this
#    value in place of its default for the initial RTT estimate.

[[spec]]
level = "MAY"
quote = '''
The client MAY compute an RTT estimate to the server as the time
period from when the first Initial packet was sent to when a Retry or
a Version Negotiation packet is received.
'''

[[spec]]
level = "MAY"
quote = '''
The client MAY use this
value in place of its default for the initial RTT estimate.
'''

