target = "https://www.rfc-editor.org/rfc/rfc9002#section-6.1.1"

# Packet Threshold
#
#    The RECOMMENDED initial value for the packet reordering threshold
#    (kPacketThreshold) is 3, based on best practices for TCP loss
#    detection [RFC5681] [RFC6675].  In order to remain similar to TCP,
#    implementations SHOULD NOT use a packet threshold less than 3; see
#    [RFC5681].
# 
#    Some networks may exhibit higher degrees of packet reordering,
#    causing a sender to detect spurious losses.  Additionally, packet
#    reordering could be more common with QUIC than TCP because network
#    elements that could observe and reorder TCP packets cannot do that
#    for QUIC and also because QUIC packet numbers are encrypted.
#    Algorithms that increase the reordering threshold after spuriously
#    detecting losses, such as RACK [RFC8985], have proven to be useful in
#    TCP and are expected to be at least as useful in QUIC.

[[spec]]
level = "SHOULD"
quote = '''
The RECOMMENDED initial value for the packet reordering threshold
(kPacketThreshold) is 3, based on best practices for TCP loss
detection [RFC5681] [RFC6675].
'''

[[spec]]
level = "SHOULD"
quote = '''
In order to remain similar to TCP,
implementations SHOULD NOT use a packet threshold less than 3; see
[RFC5681].
'''

