target = "https://www.rfc-editor.org/rfc/rfc9002#section-7.4"

# Ignoring Loss of Undecryptable Packets
#
#    During the handshake, some packet protection keys might not be
#    available when a packet arrives, and the receiver can choose to drop
#    the packet.  In particular, Handshake and 0-RTT packets cannot be
#    processed until the Initial packets arrive, and 1-RTT packets cannot
#    be processed until the handshake completes.  Endpoints MAY ignore the
#    loss of Handshake, 0-RTT, and 1-RTT packets that might have arrived
#    before the peer had packet protection keys to process those packets.
#    Endpoints MUST NOT ignore the loss of packets that were sent after
#    the earliest acknowledged packet in a given packet number space.

[[spec]]
level = "MAY"
quote = '''
Endpoints MAY ignore the
loss of Handshake, 0-RTT, and 1-RTT packets that might have arrived
before the peer had packet protection keys to process those packets.
'''

[[spec]]
level = "MUST"
quote = '''
Endpoints MUST NOT ignore the loss of packets that were sent after
the earliest acknowledged packet in a given packet number space.
'''

