target = "https://www.rfc-editor.org/rfc/rfc9002#section-7.3.1"

# Slow Start
#
#    A NewReno sender is in slow start any time the congestion window is
#    below the slow start threshold.  A sender begins in slow start
#    because the slow start threshold is initialized to an infinite value.
# 
#    While a sender is in slow start, the congestion window increases by
#    the number of bytes acknowledged when each acknowledgment is
#    processed.  This results in exponential growth of the congestion
#    window.
# 
#    The sender MUST exit slow start and enter a recovery period when a
#    packet is lost or when the ECN-CE count reported by its peer
#    increases.
# 
#    A sender reenters slow start any time the congestion window is less
#    than the slow start threshold, which only occurs after persistent
#    congestion is declared.

[[spec]]
level = "MUST"
quote = '''
The sender MUST exit slow start and enter a recovery period when a
packet is lost or when the ECN-CE count reported by its peer
increases.
'''

