target = "https://www.rfc-editor.org/rfc/rfc9002#section-7.8"

# Underutilizing the Congestion Window
#
#    When bytes in flight is smaller than the congestion window and
#    sending is not pacing limited, the congestion window is
#    underutilized.  This can happen due to insufficient application data
#    or flow control limits.  When this occurs, the congestion window
#    SHOULD NOT be increased in either slow start or congestion avoidance.
# 
#    A sender that paces packets (see Section 7.7) might delay sending
#    packets and not fully utilize the congestion window due to this
#    delay.  A sender SHOULD NOT consider itself application limited if it
#    would have fully utilized the congestion window without pacing delay.
# 
#    A sender MAY implement alternative mechanisms to update its
#    congestion window after periods of underutilization, such as those
#    proposed for TCP in [RFC7661].

[[spec]]
level = "SHOULD"
quote = '''
When this occurs, the congestion window
SHOULD NOT be increased in either slow start or congestion avoidance.
'''

[[spec]]
level = "SHOULD"
quote = '''
A sender SHOULD NOT consider itself application limited if it
would have fully utilized the congestion window without pacing delay.
'''

[[spec]]
level = "MAY"
quote = '''
A sender MAY implement alternative mechanisms to update its
congestion window after periods of underutilization, such as those
proposed for TCP in [RFC7661].
'''

