target = "https://www.rfc-editor.org/rfc/rfc9002#section-6.2.2"

# Handshakes and New Paths
#
#    Resumed connections over the same network MAY use the previous
#    connection's final smoothed RTT value as the resumed connection's
#    initial RTT.  When no previous RTT is available, the initial RTT
#    SHOULD be set to 333 milliseconds.  This results in handshakes
#    starting with a PTO of 1 second, as recommended for TCP's initial
#    RTO; see Section 2 of [RFC6298].
# 
#    A connection MAY use the delay between sending a PATH_CHALLENGE and
#    receiving a PATH_RESPONSE to set the initial RTT (see kInitialRtt in
#    Appendix A.2) for a new path, but the delay SHOULD NOT be considered
#    an RTT sample.
# 
#    When the Initial keys and Handshake keys are discarded (see
#    Section 6.4), any Initial packets and Handshake packets can no longer
#    be acknowledged, so they are removed from bytes in flight.  When
#    Initial or Handshake keys are discarded, the PTO and loss detection
#    timers MUST be reset, because discarding keys indicates forward
#    progress and the loss detection timer might have been set for a now-
#    discarded packet number space.

[[spec]]
level = "MAY"
quote = '''
Resumed connections over the same network MAY use the previous
connection's final smoothed RTT value as the resumed connection's
initial RTT.
'''

[[spec]]
level = "SHOULD"
quote = '''
When no previous RTT is available, the initial RTT
SHOULD be set to 333 milliseconds.
'''

[[spec]]
level = "SHOULD"
quote = '''
A connection MAY use the delay between sending a PATH_CHALLENGE and
receiving a PATH_RESPONSE to set the initial RTT (see kInitialRtt in
Appendix A.2) for a new path, but the delay SHOULD NOT be considered
an RTT sample.
'''

[[spec]]
level = "MUST"
quote = '''
When
Initial or Handshake keys are discarded, the PTO and loss detection
timers MUST be reset, because discarding keys indicates forward
progress and the loss detection timer might have been set for a now-
discarded packet number space.
'''

