target = "https://www.rfc-editor.org/rfc/rfc9001#section-4.1.2"

# Handshake Confirmed
#
#    In this document, the TLS handshake is considered confirmed at the
#    server when the handshake completes.  The server MUST send a
#    HANDSHAKE_DONE frame as soon as the handshake is complete.  At the
#    client, the handshake is considered confirmed when a HANDSHAKE_DONE
#    frame is received.
# 
#    Additionally, a client MAY consider the handshake to be confirmed
#    when it receives an acknowledgment for a 1-RTT packet.  This can be
#    implemented by recording the lowest packet number sent with 1-RTT
#    keys and comparing it to the Largest Acknowledged field in any
#    received 1-RTT ACK frame: once the latter is greater than or equal to
#    the former, the handshake is confirmed.

[[spec]]
level = "MUST"
quote = '''
The server MUST send a
HANDSHAKE_DONE frame as soon as the handshake is complete.
'''

[[spec]]
level = "MAY"
quote = '''
Additionally, a client MAY consider the handshake to be confirmed
when it receives an acknowledgment for a 1-RTT packet.
'''

