target = "https://www.rfc-editor.org/rfc/rfc9001#section-4.2"

# TLS Version
#
#    This document describes how TLS 1.3 [TLS13] is used with QUIC.
# 
#    In practice, the TLS handshake will negotiate a version of TLS to
#    use.  This could result in a version of TLS newer than 1.3 being
#    negotiated if both endpoints support that version.  This is
#    acceptable provided that the features of TLS 1.3 that are used by
#    QUIC are supported by the newer version.
# 
#    Clients MUST NOT offer TLS versions older than 1.3.  A badly
#    configured TLS implementation could negotiate TLS 1.2 or another
#    older version of TLS.  An endpoint MUST terminate the connection if a
#    version of TLS older than 1.3 is negotiated.

[[spec]]
level = "MUST"
quote = '''
Clients MUST NOT offer TLS versions older than 1.3.
'''

[[spec]]
level = "MUST"
quote = '''
An endpoint MUST terminate the connection if a
version of TLS older than 1.3 is negotiated.
'''

