target = "https://www.rfc-editor.org/rfc/rfc9001#section-4.7"

# HelloRetryRequest
#
#    The HelloRetryRequest message (see Section 4.1.4 of [TLS13]) can be
#    used to request that a client provide new information, such as a key
#    share, or to validate some characteristic of the client.  From the
#    perspective of QUIC, HelloRetryRequest is not differentiated from
#    other cryptographic handshake messages that are carried in Initial
#    packets.  Although it is in principle possible to use this feature
#    for address verification, QUIC implementations SHOULD instead use the
#    Retry feature; see Section 8.1 of [QUIC-TRANSPORT].

[[spec]]
level = "SHOULD"
quote = '''
Although it is in principle possible to use this feature
for address verification, QUIC implementations SHOULD instead use the
Retry feature; see Section 8.1 of [QUIC-TRANSPORT].
'''

