target = "https://www.rfc-editor.org/rfc/rfc9001#section-4.9.2"

# Discarding Handshake Keys
#
#    An endpoint MUST discard its Handshake keys when the TLS handshake is
#    confirmed (Section 4.1.2).

[[spec]]
level = "MUST"
quote = '''
An endpoint MUST discard its Handshake keys when the TLS handshake is
confirmed (Section 4.1.2).
'''

