target = "https://www.rfc-editor.org/rfc/rfc9001#section-8.3"

# Removing the EndOfEarlyData Message
#
#    The TLS EndOfEarlyData message is not used with QUIC.  QUIC does not
#    rely on this message to mark the end of 0-RTT data or to signal the
#    change to Handshake keys.
# 
#    Clients MUST NOT send the EndOfEarlyData message.  A server MUST
#    treat receipt of a CRYPTO frame in a 0-RTT packet as a connection
#    error of type PROTOCOL_VIOLATION.
# 
#    As a result, EndOfEarlyData does not appear in the TLS handshake
#    transcript.

[[spec]]
level = "MUST"
quote = '''
Clients MUST NOT send the EndOfEarlyData message.
'''

[[spec]]
level = "MUST"
quote = '''
A server MUST
treat receipt of a CRYPTO frame in a 0-RTT packet as a connection
error of type PROTOCOL_VIOLATION.
'''

