target = "https://www.rfc-editor.org/rfc/rfc9000#7"

[[exception]]
quote = '''
The cryptographic handshake MUST provide the following properties:
'''
reason = '''
TLS support is implemented through a provider and is unenforceable by
s2n-quic.
'''

