target = "https://www.rfc-editor.org/rfc/rfc8312#section-4.6"

# Fast Convergence
#
#    To improve the convergence speed of CUBIC, we add a heuristic in
#    CUBIC.  When a new flow joins the network, existing flows in the
#    network need to give up some of their bandwidth to allow the new flow
#    some room for growth if the existing flows have been using all the
#    bandwidth of the network.  To speed up this bandwidth release by
#    existing flows, the following mechanism called "fast convergence"
#    SHOULD be implemented.
# 
#    With fast convergence, when a congestion event occurs, before the
#    window reduction of the congestion window, a flow remembers the last
#    value of W_max before it updates W_max for the current congestion
#    event.  Let us call the last value of W_max to be W_last_max.
# 
#       if (W_max < W_last_max){ // should we make room for others
#           W_last_max = W_max;             // remember the last W_max
#           W_max = W_max*(1.0+beta_cubic)/2.0; // further reduce W_max
#       } else {
#           W_last_max = W_max              // remember the last W_max
#       }
# 
#    At a congestion event, if the current value of W_max is less than
#    W_last_max, this indicates that the saturation point experienced by
#    this flow is getting reduced because of the change in available
#    bandwidth.  Then we allow this flow to release more bandwidth by
#    reducing W_max further.  This action effectively lengthens the time
#    for this flow to increase its congestion window because the reduced
#    W_max forces the flow to have the plateau earlier.  This allows more
#    time for the new flow to catch up to its congestion window size.
# 
#    The fast convergence is designed for network environments with
#    multiple CUBIC flows.  In network environments with only a single
#    CUBIC flow and without any other traffic, the fast convergence SHOULD
#    be disabled.

[[spec]]
level = "SHOULD"
quote = '''
To speed up this bandwidth release by
existing flows, the following mechanism called "fast convergence"
SHOULD be implemented.
'''

[[spec]]
level = "SHOULD"
quote = '''
In network environments with only a single
CUBIC flow and without any other traffic, the fast convergence SHOULD
be disabled.
'''

