target = "https://www.rfc-editor.org/rfc/rfc8312#section-4.3"

# Concave Region
#
#    When receiving an ACK in congestion avoidance, if CUBIC is not in the
#    TCP-friendly region and cwnd is less than W_max, then CUBIC is in the
#    concave region.  In this region, cwnd MUST be incremented by
#    (W_cubic(t+RTT) - cwnd)/cwnd for each received ACK, where
#    W_cubic(t+RTT) is calculated using Eq. 1.

[[spec]]
level = "MUST"
quote = '''
In this region, cwnd MUST be incremented by
(W_cubic(t+RTT) - cwnd)/cwnd for each received ACK, where
W_cubic(t+RTT) is calculated using Eq.
'''

