target = "https://www.rfc-editor.org/rfc/rfc8312#section-4.5"

# Multiplicative Decrease
#
#    When a packet loss is detected by duplicate ACKs or a network
#    congestion is detected by ECN-Echo ACKs, CUBIC updates its W_max,
#    cwnd, and ssthresh as follows.  Parameter beta_cubic SHOULD be set to
#    0.7.
# 
#       W_max = cwnd;                 // save window size before reduction
#       ssthresh = cwnd * beta_cubic; // new slow-start threshold
#       ssthresh = max(ssthresh, 2);  // threshold is at least 2 MSS
#       cwnd = cwnd * beta_cubic;     // window reduction
# 
#    A side effect of setting beta_cubic to a value bigger than 0.5 is
#    slower convergence.  We believe that while a more adaptive setting of
#    beta_cubic could result in faster convergence, it will make the
#    analysis of CUBIC much harder.  This adaptive adjustment of
#    beta_cubic is an item for the next version of CUBIC.

[[spec]]
level = "SHOULD"
quote = '''
Parameter beta_cubic SHOULD be set to
0.7.
'''

