# https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#13.1
#
# 13.1.  Packet Processing
#
# A packet MUST NOT be acknowledged until packet protection has been
# successfully removed and all frames contained in the packet have been
# processed.  For STREAM frames, this means the data has been enqueued
# in preparation to be received by the application protocol, but it
# does not require that data is delivered and consumed.
# 
# Once the packet has been fully processed, a receiver acknowledges
# receipt by sending one or more ACK frames containing the packet
# number of the received packet.
# 
# An endpoint SHOULD treat receipt of an acknowledgment for a packet it
# did not send as a connection error of type PROTOCOL_VIOLATION, if it
# is able to detect the condition.

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#13.1"
level = "MUST"
quote = '''
A packet MUST NOT be acknowledged until packet protection has been
successfully removed and all frames contained in the packet have been
processed.
'''

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#13.1"
level = "SHOULD"
quote = '''
An endpoint SHOULD treat receipt of an acknowledgment for a packet it
did not send as a connection error of type PROTOCOL_VIOLATION, if it
is able to detect the condition.
'''

