# https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#19.18
#
# 19.18.  PATH_RESPONSE Frames
#
# A PATH_RESPONSE frame (type=0x1b) is sent in response to a
# PATH_CHALLENGE frame.
# 
# PATH_RESPONSE frames are formatted as shown in Figure 42, which is
# identical to the PATH_CHALLENGE frame (Section 19.17).
# 
# PATH_RESPONSE Frame {
#   Type (i) = 0x1b,
#   Data (64),
# }
# 
#                 Figure 42: PATH_RESPONSE Frame Format
# 
# If the content of a PATH_RESPONSE frame does not match the content of
# a PATH_CHALLENGE frame previously sent by the endpoint, the endpoint
# MAY generate a connection error of type PROTOCOL_VIOLATION.

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#19.18"
level = "MAY"
quote = '''
If the content of a PATH_RESPONSE frame does not match the content of
a PATH_CHALLENGE frame previously sent by the endpoint, the endpoint
MAY generate a connection error of type PROTOCOL_VIOLATION.
'''

