# https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#21.11
#
# 21.11.  Version Downgrade
#
# This document defines QUIC Version Negotiation packets in Section 6
# that can be used to negotiate the QUIC version used between two
# endpoints.  However, this document does not specify how this
# negotiation will be performed between this version and subsequent
# future versions.  In particular, Version Negotiation packets do not
# contain any mechanism to prevent version downgrade attacks.  Future
# versions of QUIC that use Version Negotiation packets MUST define a
# mechanism that is robust against version downgrade attacks.

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#21.11"
level = "MUST"
quote = '''
Future
versions of QUIC that use Version Negotiation packets MUST define a
mechanism that is robust against version downgrade attacks.
'''

