# https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#21.12
#
# 21.12.  Targeted Attacks by Routing
#
# Deployments should limit the ability of an attacker to target a new
# connection to a particular server instance.  This means that client-
# controlled fields, such as the initial Destination Connection ID used
# on Initial and 0-RTT packets SHOULD NOT be used by themselves to make
# routing decisions.  Ideally, routing decisions are made independently
# of client-selected values; a Source Connection ID can be selected to
# route later packets to the same server.

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#21.12"
level = "SHOULD"
quote = '''
This means that client-
controlled fields, such as the initial Destination Connection ID used
on Initial and 0-RTT packets SHOULD NOT be used by themselves to make
routing decisions.
'''

