# https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#22.1.1
#
# 22.1.1.  Provisional Registrations
#
# Provisional registration of codepoints are intended to allow for
# private use and experimentation with extensions to QUIC.  Provisional
# registrations only require the inclusion of the codepoint value and
# contact information.  However, provisional registrations could be
# reclaimed and reassigned for another purpose.
# 
# Provisional registrations require Expert Review, as defined in
# Section 4.5 of [RFC8126].  Designated expert(s) are advised that only
# registrations for an excessive proportion of remaining codepoint
# space or the very first unassigned value (see Section 22.1.2) can be
# rejected.
# 
# Provisional registrations will include a date field that indicates
# when the registration was last updated.  A request to update the date
# on any provisional registration can be made without review from the
# designated expert(s).
# 
# All QUIC registries include the following fields to support
# provisional registration:
# 
# Value:  The assigned codepoint.
# 
# Status:  "Permanent" or "Provisional".
# 
# Specification:  A reference to a publicly available specification for
#    the value.
# 
# Date:  The date of last update to the registration.
# 
# Change Controller:  The entity that is responsible for the definition
#    of the registration.
# 
# Contact:  Contact details for the registrant.
# 
# Notes:  Supplementary notes about the registration.
# 
# Provisional registrations MAY omit the Specification and Notes
# fields, plus any additional fields that might be required for a
# permanent registration.  The Date field is not required as part of
# requesting a registration as it is set to the date the registration
# is created or updated.

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#22.1.1"
level = "MAY"
quote = '''
Provisional registrations MAY omit the Specification and Notes
fields, plus any additional fields that might be required for a
permanent registration.
'''

