# https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#22.3
#
# 22.3.  QUIC Frame Types Registry
#
# IANA [SHALL add/has added] a registry for "QUIC Frame Types" under a
# "QUIC" heading.
# 
# The "QUIC Frame Types" registry governs a 62-bit space.  This
# registry follows the registration policy from Section 22.1.
# Permanent registrations in this registry are assigned using the
# Specification Required policy ([RFC8126]), except for values between
# 0x00 and 0x3f (in hexadecimal; inclusive), which are assigned using
# Standards Action or IESG Approval as defined in Section 4.9 and 4.10
# of [RFC8126].
# 
# In addition to the fields in Section 22.1.1, permanent registrations
# in this registry MUST include the following field:
# 
# Frame Name:  A short mnemonic for the frame type.
# 
# In addition to the advice in Section 22.1, specifications for new
# permanent registrations SHOULD describe the means by which an
# endpoint might determine that it can send the identified type of
# frame.  An accompanying transport parameter registration is expected
# for most registrations; see Section 22.2.  Specifications for
# permanent registrations also need to describe the format and assigned
# semantics of any fields in the frame.
# 
# The initial contents of this registry are tabulated in Table 3.  Note
# that the registry does not include the "Pkts" and "Spec" columns from
# Table 3.

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#22.3"
level = "SHALL"
quote = '''
IANA [SHALL add/has added] a registry for "QUIC Frame Types" under a
"QUIC" heading.
'''

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#22.3"
level = "MUST"
quote = '''
In addition to the fields in Section 22.1.1, permanent registrations
in this registry MUST include the following field:
'''

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#22.3"
level = "SHOULD"
quote = '''
In addition to the advice in Section 22.1, specifications for new
permanent registrations SHOULD describe the means by which an
endpoint might determine that it can send the identified type of
frame.
'''

