# https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#6.2
#
# 6.2.  Handling Version Negotiation Packets
#
# Version Negotiation packets are designed to allow future versions of
# QUIC to negotiate the version in use between endpoints.  Future
# versions of QUIC might change how implementations that support
# multiple versions of QUIC react to Version Negotiation packets when
# attempting to establish a connection using this version.
# 
# A client that supports only this version of QUIC MUST abandon the
# current connection attempt if it receives a Version Negotiation
# packet, with the following two exceptions.  A client MUST discard any
# Version Negotiation packet if it has received and successfully
# processed any other packet, including an earlier Version Negotiation
# packet.  A client MUST discard a Version Negotiation packet that
# lists the QUIC version selected by the client.
# 
# How to perform version negotiation is left as future work defined by
# future versions of QUIC.  In particular, that future work will ensure
# robustness against version downgrade attacks; see Section 21.11.

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#6.2"
level = "MUST"
quote = '''
A client that supports only this version of QUIC MUST abandon the
current connection attempt if it receives a Version Negotiation
packet, with the following two exceptions.
'''

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#6.2"
level = "MUST"
quote = '''
A client MUST discard any
Version Negotiation packet if it has received and successfully
processed any other packet, including an earlier Version Negotiation
packet.
'''

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#6.2"
level = "MUST"
quote = '''
A client MUST discard a Version Negotiation packet that
lists the QUIC version selected by the client.
'''

