# https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#9.7
#
# 9.7.  Use of IPv6 Flow-Label and Migration
#
# Endpoints that send data using IPv6 SHOULD apply an IPv6 flow label
# in compliance with [RFC6437], unless the local API does not allow
# setting IPv6 flow labels.
# 
# The IPv6 flow label SHOULD be a pseudo-random function of the source
# and destination addresses, source and destination UDP ports, and the
# Destination Connection ID field.  The flow label generation MUST be
# designed to minimize the chances of linkability with a previously
# used flow label, as this would enable correlating activity on
# multiple paths; see Section 9.5.
# 
# A possible implementation is to compute the flow label as a
# cryptographic hash function of the source and destination addresses,
# source and destination UDP ports, Destination Connection ID field,
# and a local secret.

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#9.7"
level = "SHOULD"
quote = '''
Endpoints that send data using IPv6 SHOULD apply an IPv6 flow label
in compliance with [RFC6437], unless the local API does not allow
setting IPv6 flow labels.
'''

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#9.7"
level = "SHOULD"
quote = '''
The IPv6 flow label SHOULD be a pseudo-random function of the source
and destination addresses, source and destination UDP ports, and the
Destination Connection ID field.
'''

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-transport-32.txt#9.7"
level = "MUST"
quote = '''
The flow label generation MUST be
designed to minimize the chances of linkability with a previously
used flow label, as this would enable correlating activity on
multiple paths; see Section 9.5.
'''

