target = "https://www.rfc-editor.org/rfc/rfc9002#section-6.1"

[[TODO]]
quote = '''
Implementations with adaptive time
thresholds MAY choose to start with smaller initial reordering
thresholds to minimize recovery latency.
'''
feature = "Adaptive loss thresholds"
tracking-issue = "252"
