target = "https://www.rfc-editor.org/rfc/rfc9002#section-6.1.2"

[[TODO]]
quote = '''
Implementations MAY experiment with absolute thresholds, thresholds
from previous connections, adaptive thresholds, or the including of
RTT variation.
'''
feature = "Adaptive loss thresholds"
tracking-issue = "252"
