target = "https://www.rfc-editor.org/rfc/rfc9001#section-9.4"

[[exception]]
quote = '''
Future header protection variants based on this construction MUST use
a PRF to ensure equivalent security guarantees.
'''
reason = '''
s2n-quic does not use or define any additional header protection variants
'''

