[default]
binary = false
check-filename = true

[default.extend-identifiers]
# in crypto/retry.rs there is a false positive on hex values - ignore it here
0f2496ba = "0f2496ba"

[default.extend-words]
# msg_controllen is a standard POSIX field name in msghdr struct
controllen = "controllen"
# ECN Capable Transport
ect = "ect"
# num_rational uses "numer" as short for "numerator"
numer = "numer"
# Packet number
pn = "pn"
# retransmission timeout
RTO = "RTO"
# Web Services
WS = "WS"

[files]
extend-exclude = [
    "*.snap",
    "*.bin",
    "*.der",
    "*.pem",
    "**/specs/**/*",
    "**/wireshark_sys*",
]
