target = "https://www.rfc-editor.org/rfc/rfc9002#section-6.2.4"

[[exception]]
target = "https://www.rfc-editor.org/rfc/rfc9002#section-6.2.4"
quote = '''
Alternatively, instead of sending an ack-eliciting packet, the sender
MAY mark any packets still in flight as lost.
'''
reason = '''
This increases the risk that loss is
declared too aggressively, resulting in an unnecessary rate reduction
by the congestion controller.
'''
