target = "https://www.rfc-editor.org/rfc/rfc9002#section-6.3"

[[exception]]
quote = '''
The client MAY compute an RTT estimate to the server as the time
period from when the first Initial packet was sent to when a Retry or
a Version Negotiation packet is received.
'''
reason = '''
There isn't much benefit from doing this since the initial RTT is
discarded after the first RTT sample.
'''

[[exception]]
quote = '''
The client MAY use this
value in place of its default for the initial RTT estimate.
'''
reason = '''
There isn't much benefit from doing this since the initial RTT is
discarded after the first RTT sample.
'''
