target = "https://www.rfc-editor.org/rfc/rfc8899#section-4.6.2"

[[TODO]]
quote = '''
PTB messages that have been validated MAY be utilized by the DPLPMTUD
algorithm but MUST NOT be used directly to set the PLPMTU.
'''
feature = "Incorporate PTB messages into DPLPMTUD"
tracking-issue = "628"

[[TODO]]
quote = '''
MIN_PLPMTU < PL_PTB_SIZE < BASE_PLPMTU
*  A robust PL MAY enter an error state (see Section 5.2) for an
IPv4 path when the PL_PTB_SIZE reported in the PTB message is
larger than or equal to 68 bytes [RFC0791] and when this is
less than the BASE_PLPMTU.
'''
feature = "Incorporate PTB messages into DPLPMTUD"
tracking-issue = "628"

[[TODO]]
quote = '''
*  A robust PL MAY enter an error state (see Section 5.2) for an
IPv6 path when the PL_PTB_SIZE reported in the PTB message is
larger than or equal to 1280 bytes [RFC8200] and when this is
less than the BASE_PLPMTU.
'''
feature = "Incorporate PTB messages into DPLPMTUD"
tracking-issue = "628"

[[TODO]]
quote = '''
The PLPMTU SHOULD
be set to BASE_PLPMTU (the PLPMTU is reduced to the BASE_PLPMTU
to avoid unnecessary packet loss when a black hole is
encountered).
'''
feature = "Incorporate PTB messages into DPLPMTUD"
tracking-issue = "628"
