target = "https://www.rfc-editor.org/rfc/rfc8899#section-8"

[[TODO]]
quote = '''
A node supporting DPLPMTUD
MUST therefore appropriately validate the payload of PTB messages to
ensure these are received in response to transmitted traffic (i.e., a
reported error condition that corresponds to a datagram actually sent
by the path layer, see Section 4.6.1).
'''
feature = "Incorporate PTB messages into DPLPMTUD"
tracking-issue = "628"

[[TODO]]
quote = '''
This processing
SHOULD be limited to avoid a denial-of-service attack when arbitrary
headers are included.
'''
feature = "Incorporate PTB messages into DPLPMTUD"
tracking-issue = "628"