target = "https://www.rfc-editor.org/rfc/rfc9000#section-19.15"

[[exception]]
target = "https://www.rfc-editor.org/rfc/rfc9000#section-19.15"
quote = '''
An endpoint MUST NOT send this frame if it currently requires that
its peer send packets with a zero-length Destination Connection ID.
'''
reason = "s2n-quic never requires the peer to send zero-length Destination Connection ID"

