target = "https://www.rfc-editor.org/rfc/rfc9000#section-7.4.2"

# New Transport Parameters
#
#    New transport parameters can be used to negotiate new protocol
#    behavior.  An endpoint MUST ignore transport parameters that it does
#    not support.  The absence of a transport parameter therefore disables
#    any optional protocol feature that is negotiated using the parameter.
#    As described in Section 18.1, some identifiers are reserved in order
#    to exercise this requirement.
# 
#    A client that does not understand a transport parameter can discard
#    it and attempt 0-RTT on subsequent connections.  However, if the
#    client adds support for a discarded transport parameter, it risks
#    violating the constraints that the transport parameter establishes if
#    it attempts 0-RTT.  New transport parameters can avoid this problem
#    by setting a default of the most conservative value.  Clients can
#    avoid this problem by remembering all parameters, even those not
#    currently supported.
# 
#    New transport parameters can be registered according to the rules in
#    Section 22.3.

[[spec]]
level = "MUST"
quote = '''
An endpoint MUST ignore transport parameters that it does
not support.
'''

