target = "https://www.rfc-editor.org/rfc/rfc9000#section-19.18"

# PATH_RESPONSE Frames
#
#    A PATH_RESPONSE frame (type=0x1b) is sent in response to a
#    PATH_CHALLENGE frame.
# 
#    PATH_RESPONSE frames are formatted as shown in Figure 42.  The format
#    of a PATH_RESPONSE frame is identical to that of the PATH_CHALLENGE
#    frame; see Section 19.17.
# 
#    PATH_RESPONSE Frame {
#      Type (i) = 0x1b,
#      Data (64),
#    }
# 
#                    Figure 42: PATH_RESPONSE Frame Format
# 
#    If the content of a PATH_RESPONSE frame does not match the content of
#    a PATH_CHALLENGE frame previously sent by the endpoint, the endpoint
#    MAY generate a connection error of type PROTOCOL_VIOLATION.

[[spec]]
level = "MAY"
quote = '''
If the content of a PATH_RESPONSE frame does not match the content of
a PATH_CHALLENGE frame previously sent by the endpoint, the endpoint
MAY generate a connection error of type PROTOCOL_VIOLATION.
'''

