target = "https://www.rfc-editor.org/rfc/rfc9000#section-19.13"

# STREAM_DATA_BLOCKED Frames
#
#    A sender SHOULD send a STREAM_DATA_BLOCKED frame (type=0x15) when it
#    wishes to send data but is unable to do so due to stream-level flow
#    control.  This frame is analogous to DATA_BLOCKED (Section 19.12).
# 
#    An endpoint that receives a STREAM_DATA_BLOCKED frame for a send-only
#    stream MUST terminate the connection with error STREAM_STATE_ERROR.
# 
#    STREAM_DATA_BLOCKED frames are formatted as shown in Figure 37.
# 
#    STREAM_DATA_BLOCKED Frame {
#      Type (i) = 0x15,
#      Stream ID (i),
#      Maximum Stream Data (i),
#    }
# 
#                 Figure 37: STREAM_DATA_BLOCKED Frame Format
# 
#    STREAM_DATA_BLOCKED frames contain the following fields:
# 
#    Stream ID:  A variable-length integer indicating the stream that is
#       blocked due to flow control.
# 
#    Maximum Stream Data:  A variable-length integer indicating the offset
#       of the stream at which the blocking occurred.

[[spec]]
level = "SHOULD"
quote = '''
A sender SHOULD send a STREAM_DATA_BLOCKED frame (type=0x15) when it
wishes to send data but is unable to do so due to stream-level flow
control.
'''

[[spec]]
level = "MUST"
quote = '''
An endpoint that receives a STREAM_DATA_BLOCKED frame for a send-only
stream MUST terminate the connection with error STREAM_STATE_ERROR.
'''

