target = "https://www.rfc-editor.org/rfc/rfc9000#section-9.1"

# Probing a New Path
#
#    An endpoint MAY probe for peer reachability from a new local address
#    using path validation (Section 8.2) prior to migrating the connection
#    to the new local address.  Failure of path validation simply means
#    that the new path is not usable for this connection.  Failure to
#    validate a path does not cause the connection to end unless there are
#    no valid alternative paths available.
# 
#    PATH_CHALLENGE, PATH_RESPONSE, NEW_CONNECTION_ID, and PADDING frames
#    are "probing frames", and all other frames are "non-probing frames".
#    A packet containing only probing frames is a "probing packet", and a
#    packet containing any other frame is a "non-probing packet".

[[spec]]
level = "MAY"
quote = '''
An endpoint MAY probe for peer reachability from a new local address
using path validation (Section 8.2) prior to migrating the connection
to the new local address.
'''

