target = "https://www.rfc-editor.org/rfc/rfc9000#section-10"

# Connection Termination
#
#    An established QUIC connection can be terminated in one of three
#    ways:
# 
#    *  idle timeout (Section 10.1)
# 
#    *  immediate close (Section 10.2)
# 
#    *  stateless reset (Section 10.3)
# 
#    An endpoint MAY discard connection state if it does not have a
#    validated path on which it can send packets; see Section 8.2.

[[spec]]
level = "MAY"
quote = '''
An endpoint MAY discard connection state if it does not have a
validated path on which it can send packets; see Section 8.2.
'''

