target = "https://www.rfc-editor.org/rfc/rfc9000#section-14.4"

# Sending QUIC PMTU Probes
#
#    PMTU probes are ack-eliciting packets.
# 
#    Endpoints could limit the content of PMTU probes to PING and PADDING
#    frames, since packets that are larger than the current maximum
#    datagram size are more likely to be dropped by the network.  Loss of
#    a QUIC packet that is carried in a PMTU probe is therefore not a
#    reliable indication of congestion and SHOULD NOT trigger a congestion
#    control reaction; see Item 7 in Section 3 of [DPLPMTUD].  However,
#    PMTU probes consume congestion window, which could delay subsequent
#    transmission by an application.

[[spec]]
level = "SHOULD"
quote = '''
Loss of
a QUIC packet that is carried in a PMTU probe is therefore not a
reliable indication of congestion and SHOULD NOT trigger a congestion
control reaction; see Item 7 in Section 3 of [DPLPMTUD].
'''

