target = "https://www.rfc-editor.org/rfc/rfc9000#section-21.12"

# Version Downgrade
#
#    This document defines QUIC Version Negotiation packets (Section 6),
#    which can be used to negotiate the QUIC version used between two
#    endpoints.  However, this document does not specify how this
#    negotiation will be performed between this version and subsequent
#    future versions.  In particular, Version Negotiation packets do not
#    contain any mechanism to prevent version downgrade attacks.  Future
#    versions of QUIC that use Version Negotiation packets MUST define a
#    mechanism that is robust against version downgrade attacks.

[[spec]]
level = "MUST"
quote = '''
Future
versions of QUIC that use Version Negotiation packets MUST define a
mechanism that is robust against version downgrade attacks.
'''

