target = "https://www.rfc-editor.org/rfc/rfc9000#section-6"

# Version Negotiation
#
#    Version negotiation allows a server to indicate that it does not
#    support the version the client used.  A server sends a Version
#    Negotiation packet in response to each packet that might initiate a
#    new connection; see Section 5.2 for details.
# 
#    The size of the first packet sent by a client will determine whether
#    a server sends a Version Negotiation packet.  Clients that support
#    multiple QUIC versions SHOULD ensure that the first UDP datagram they
#    send is sized to the largest of the minimum datagram sizes from all
#    versions they support, using PADDING frames (Section 19.1) as
#    necessary.  This ensures that the server responds if there is a
#    mutually supported version.  A server might not send a Version
#    Negotiation packet if the datagram it receives is smaller than the
#    minimum size specified in a different version; see Section 14.1.

[[spec]]
level = "SHOULD"
quote = '''
Clients that support
multiple QUIC versions SHOULD ensure that the first UDP datagram they
send is sized to the largest of the minimum datagram sizes from all
versions they support, using PADDING frames (Section 19.1) as
necessary.
'''

