target = "https://www.rfc-editor.org/rfc/rfc9000#section-22.1.2"

# Selecting Codepoints
#
#    New requests for codepoints from QUIC registries SHOULD use a
#    randomly selected codepoint that excludes both existing allocations
#    and the first unallocated codepoint in the selected space.  Requests
#    for multiple codepoints MAY use a contiguous range.  This minimizes
#    the risk that differing semantics are attributed to the same
#    codepoint by different implementations.
# 
#    The use of the first unassigned codepoint is reserved for allocation
#    using the Standards Action policy; see Section 4.9 of [RFC8126].  The
#    early codepoint assignment process [EARLY-ASSIGN] can be used for
#    these values.
# 
#    For codepoints that are encoded in variable-length integers
#    (Section 16), such as frame types, codepoints that encode to four or
#    eight bytes (that is, values 2^14 and above) SHOULD be used unless
#    the usage is especially sensitive to having a longer encoding.
# 
#    Applications to register codepoints in QUIC registries MAY include a
#    requested codepoint as part of the registration.  IANA MUST allocate
#    the selected codepoint if the codepoint is unassigned and the
#    requirements of the registration policy are met.

[[spec]]
level = "SHOULD"
quote = '''
New requests for codepoints from QUIC registries SHOULD use a
randomly selected codepoint that excludes both existing allocations
and the first unallocated codepoint in the selected space.
'''

[[spec]]
level = "MAY"
quote = '''
Requests
for multiple codepoints MAY use a contiguous range.
'''

[[spec]]
level = "SHOULD"
quote = '''
For codepoints that are encoded in variable-length integers
(Section 16), such as frame types, codepoints that encode to four or
eight bytes (that is, values 2^14 and above) SHOULD be used unless
the usage is especially sensitive to having a longer encoding.
'''

[[spec]]
level = "MAY"
quote = '''
Applications to register codepoints in QUIC registries MAY include a
requested codepoint as part of the registration.
'''

[[spec]]
level = "MUST"
quote = '''
IANA MUST allocate
the selected codepoint if the codepoint is unassigned and the
requirements of the registration policy are met.
'''

