target = "https://www.rfc-editor.org/rfc/rfc9000#section-5.2.3"

# Considerations for Simple Load Balancers
#
#    A server deployment could load-balance among servers using only
#    source and destination IP addresses and ports.  Changes to the
#    client's IP address or port could result in packets being forwarded
#    to the wrong server.  Such a server deployment could use one of the
#    following methods for connection continuity when a client's address
#    changes.
# 
#    *  Servers could use an out-of-band mechanism to forward packets to
#       the correct server based on connection ID.
# 
#    *  If servers can use a dedicated server IP address or port, other
#       than the one that the client initially connects to, they could use
#       the preferred_address transport parameter to request that clients
#       move connections to that dedicated address.  Note that clients
#       could choose not to use the preferred address.
# 
#    A server in a deployment that does not implement a solution to
#    maintain connection continuity when the client address changes SHOULD
#    indicate that migration is not supported by using the
#    disable_active_migration transport parameter.  The
#    disable_active_migration transport parameter does not prohibit
#    connection migration after a client has acted on a preferred_address
#    transport parameter.
# 
#    Server deployments that use this simple form of load balancing MUST
#    avoid the creation of a stateless reset oracle; see Section 21.11.

[[spec]]
level = "SHOULD"
quote = '''
A server in a deployment that does not implement a solution to
maintain connection continuity when the client address changes SHOULD
indicate that migration is not supported by using the
disable_active_migration transport parameter.
'''

[[spec]]
level = "MUST"
quote = '''
Server deployments that use this simple form of load balancing MUST
avoid the creation of a stateless reset oracle; see Section 21.11.
'''

