target = "https://www.rfc-editor.org/rfc/rfc9000#section-22.1.3"

# Reclaiming Provisional Codepoints
#
#    A request might be made to remove an unused provisional registration
#    from the registry to reclaim space in a registry, or a portion of the
#    registry (such as the 64-16383 range for codepoints that use
#    variable-length encodings).  This SHOULD be done only for the
#    codepoints with the earliest recorded date, and entries that have
#    been updated less than a year prior SHOULD NOT be reclaimed.
# 
#    A request to remove a codepoint MUST be reviewed by the designated
#    experts.  The experts MUST attempt to determine whether the codepoint
#    is still in use.  Experts are advised to contact the listed contacts
#    for the registration, plus as wide a set of protocol implementers as
#    possible in order to determine whether any use of the codepoint is
#    known.  The experts are also advised to allow at least four weeks for
#    responses.
# 
#    If any use of the codepoints is identified by this search or a
#    request to update the registration is made, the codepoint MUST NOT be
#    reclaimed.  Instead, the date on the registration is updated.  A note
#    might be added for the registration recording relevant information
#    that was learned.
# 
#    If no use of the codepoint was identified and no request was made to
#    update the registration, the codepoint MAY be removed from the
#    registry.
# 
#    This review and consultation process also applies to requests to
#    change a provisional registration into a permanent registration,
#    except that the goal is not to determine whether there is no use of
#    the codepoint but to determine that the registration is an accurate
#    representation of any deployed usage.

[[spec]]
level = "SHOULD"
quote = '''
This SHOULD be done only for the
codepoints with the earliest recorded date, and entries that have
been updated less than a year prior SHOULD NOT be reclaimed.
'''

[[spec]]
level = "SHOULD"
quote = '''
This SHOULD be done only for the
codepoints with the earliest recorded date, and entries that have
been updated less than a year prior SHOULD NOT be reclaimed.
'''

[[spec]]
level = "MUST"
quote = '''
A request to remove a codepoint MUST be reviewed by the designated
experts.
'''

[[spec]]
level = "MUST"
quote = '''
The experts MUST attempt to determine whether the codepoint
is still in use.
'''

[[spec]]
level = "MUST"
quote = '''
If any use of the codepoints is identified by this search or a
request to update the registration is made, the codepoint MUST NOT be
reclaimed.
'''

[[spec]]
level = "MAY"
quote = '''
If no use of the codepoint was identified and no request was made to
update the registration, the codepoint MAY be removed from the
registry.
'''

