target = "https://www.rfc-editor.org/rfc/rfc9000#section-15"

# Versions
#
#    QUIC versions are identified using a 32-bit unsigned number.
# 
#    The version 0x00000000 is reserved to represent version negotiation.
#    This version of the specification is identified by the number
#    0x00000001.
# 
#    Other versions of QUIC might have different properties from this
#    version.  The properties of QUIC that are guaranteed to be consistent
#    across all versions of the protocol are described in
#    [QUIC-INVARIANTS].
# 
#    Version 0x00000001 of QUIC uses TLS as a cryptographic handshake
#    protocol, as described in [QUIC-TLS].
# 
#    Versions with the most significant 16 bits of the version number
#    cleared are reserved for use in future IETF consensus documents.
# 
#    Versions that follow the pattern 0x?a?a?a?a are reserved for use in
#    forcing version negotiation to be exercised -- that is, any version
#    number where the low four bits of all bytes is 1010 (in binary).  A
#    client or server MAY advertise support for any of these reserved
#    versions.
# 
#    Reserved version numbers will never represent a real protocol; a
#    client MAY use one of these version numbers with the expectation that
#    the server will initiate version negotiation; a server MAY advertise
#    support for one of these versions and can expect that clients ignore
#    the value.

[[spec]]
level = "MAY"
quote = '''
A
client or server MAY advertise support for any of these reserved
versions.
'''

[[spec]]
level = "MAY"
quote = '''
Reserved version numbers will never represent a real protocol; a
client MAY use one of these version numbers with the expectation that
the server will initiate version negotiation; a server MAY advertise
support for one of these versions and can expect that clients ignore
the value.
'''

[[spec]]
level = "MAY"
quote = '''
Reserved version numbers will never represent a real protocol; a
client MAY use one of these version numbers with the expectation that
the server will initiate version negotiation; a server MAY advertise
support for one of these versions and can expect that clients ignore
the value.
'''

