target = "https://www.rfc-editor.org/rfc/rfc9000#section-13.2.6"

# ACK Frames and Packet Protection
#
#    ACK frames MUST only be carried in a packet that has the same packet
#    number space as the packet being acknowledged; see Section 12.1.  For
#    instance, packets that are protected with 1-RTT keys MUST be
#    acknowledged in packets that are also protected with 1-RTT keys.
# 
#    Packets that a client sends with 0-RTT packet protection MUST be
#    acknowledged by the server in packets protected by 1-RTT keys.  This
#    can mean that the client is unable to use these acknowledgments if
#    the server cryptographic handshake messages are delayed or lost.
#    Note that the same limitation applies to other data sent by the
#    server protected by the 1-RTT keys.

[[spec]]
level = "MUST"
quote = '''
ACK frames MUST only be carried in a packet that has the same packet
number space as the packet being acknowledged; see Section 12.1.
'''

[[spec]]
level = "MUST"
quote = '''
For
instance, packets that are protected with 1-RTT keys MUST be
acknowledged in packets that are also protected with 1-RTT keys.
'''

[[spec]]
level = "MUST"
quote = '''
Packets that a client sends with 0-RTT packet protection MUST be
acknowledged by the server in packets protected by 1-RTT keys.
'''

