target = "https://www.rfc-editor.org/rfc/rfc9000#section-19.9"

# MAX_DATA Frames
#
#    A MAX_DATA frame (type=0x10) is used in flow control to inform the
#    peer of the maximum amount of data that can be sent on the connection
#    as a whole.
# 
#    MAX_DATA frames are formatted as shown in Figure 33.
# 
#    MAX_DATA Frame {
#      Type (i) = 0x10,
#      Maximum Data (i),
#    }
# 
#                       Figure 33: MAX_DATA Frame Format
# 
#    MAX_DATA frames contain the following field:
# 
#    Maximum Data:  A variable-length integer indicating the maximum
#       amount of data that can be sent on the entire connection, in units
#       of bytes.
# 
#    All data sent in STREAM frames counts toward this limit.  The sum of
#    the final sizes on all streams -- including streams in terminal
#    states -- MUST NOT exceed the value advertised by a receiver.  An
#    endpoint MUST terminate a connection with an error of type
#    FLOW_CONTROL_ERROR if it receives more data than the maximum data
#    value that it has sent.  This includes violations of remembered
#    limits in Early Data; see Section 7.4.1.

[[spec]]
level = "MUST"
quote = '''
The sum of
the final sizes on all streams -- including streams in terminal
states -- MUST NOT exceed the value advertised by a receiver.
'''

[[spec]]
level = "MUST"
quote = '''
An
endpoint MUST terminate a connection with an error of type
FLOW_CONTROL_ERROR if it receives more data than the maximum data
value that it has sent.
'''

