target = "https://www.rfc-editor.org/rfc/rfc9000#section-5.2.1"

# Client Packet Handling
#
#    Valid packets sent to clients always include a Destination Connection
#    ID that matches a value the client selects.  Clients that choose to
#    receive zero-length connection IDs can use the local address and port
#    to identify a connection.  Packets that do not match an existing
#    connection -- based on Destination Connection ID or, if this value is
#    zero length, local IP address and port -- are discarded.
# 
#    Due to packet reordering or loss, a client might receive packets for
#    a connection that are encrypted with a key it has not yet computed.
#    The client MAY drop these packets, or it MAY buffer them in
#    anticipation of later packets that allow it to compute the key.
# 
#    If a client receives a packet that uses a different version than it
#    initially selected, it MUST discard that packet.

[[spec]]
level = "MAY"
quote = '''
The client MAY drop these packets, or it MAY buffer them in
anticipation of later packets that allow it to compute the key.
'''

[[spec]]
level = "MAY"
quote = '''
The client MAY drop these packets, or it MAY buffer them in
anticipation of later packets that allow it to compute the key.
'''

[[spec]]
level = "MUST"
quote = '''
If a client receives a packet that uses a different version than it
initially selected, it MUST discard that packet.
'''

