target = "https://www.rfc-editor.org/rfc/rfc9000#section-2.3"

# Stream Prioritization
#
#    Stream multiplexing can have a significant effect on application
#    performance if resources allocated to streams are correctly
#    prioritized.
# 
#    QUIC does not provide a mechanism for exchanging prioritization
#    information.  Instead, it relies on receiving priority information
#    from the application.
# 
#    A QUIC implementation SHOULD provide ways in which an application can
#    indicate the relative priority of streams.  An implementation uses
#    information provided by the application to determine how to allocate
#    resources to active streams.

[[spec]]
level = "SHOULD"
quote = '''
A QUIC implementation SHOULD provide ways in which an application can
indicate the relative priority of streams.
'''

