target = "https://www.rfc-editor.org/rfc/rfc9000#section-4.4"

# Handling Stream Cancellation
#
#    Endpoints need to eventually agree on the amount of flow control
#    credit that has been consumed on every stream, to be able to account
#    for all bytes for connection-level flow control.
# 
#    On receipt of a RESET_STREAM frame, an endpoint will tear down state
#    for the matching stream and ignore further data arriving on that
#    stream.
# 
#    RESET_STREAM terminates one direction of a stream abruptly.  For a
#    bidirectional stream, RESET_STREAM has no effect on data flow in the
#    opposite direction.  Both endpoints MUST maintain flow control state
#    for the stream in the unterminated direction until that direction
#    enters a terminal state.

[[spec]]
level = "MUST"
quote = '''
Both endpoints MUST maintain flow control state
for the stream in the unterminated direction until that direction
enters a terminal state.
'''

