target = "https://www.rfc-editor.org/rfc/rfc9000#section-8.1.1"

# Token Construction
#
#    A token sent in a NEW_TOKEN frame or a Retry packet MUST be
#    constructed in a way that allows the server to identify how it was
#    provided to a client.  These tokens are carried in the same field but
#    require different handling from servers.

[[spec]]
level = "MUST"
quote = '''
A token sent in a NEW_TOKEN frame or a Retry packet MUST be
constructed in a way that allows the server to identify how it was
provided to a client.
'''

