target = "https://www.rfc-editor.org/rfc/rfc9000#section-11.2"

# Stream Errors
#
#    If an application-level error affects a single stream but otherwise
#    leaves the connection in a recoverable state, the endpoint can send a
#    RESET_STREAM frame (Section 19.4) with an appropriate error code to
#    terminate just the affected stream.
# 
#    Resetting a stream without the involvement of the application
#    protocol could cause the application protocol to enter an
#    unrecoverable state.  RESET_STREAM MUST only be instigated by the
#    application protocol that uses QUIC.
# 
#    The semantics of the application error code carried in RESET_STREAM
#    are defined by the application protocol.  Only the application
#    protocol is able to cause a stream to be terminated.  A local
#    instance of the application protocol uses a direct API call, and a
#    remote instance uses the STOP_SENDING frame, which triggers an
#    automatic RESET_STREAM.
# 
#    Application protocols SHOULD define rules for handling streams that
#    are prematurely canceled by either endpoint.

[[spec]]
level = "MUST"
quote = '''
RESET_STREAM MUST only be instigated by the
application protocol that uses QUIC.
'''

[[spec]]
level = "SHOULD"
quote = '''
Application protocols SHOULD define rules for handling streams that
are prematurely canceled by either endpoint.
'''

