target = "https://www.rfc-editor.org/rfc/rfc9000#section-6.3"

# Using Reserved Versions
#
#    For a server to use a new version in the future, clients need to
#    correctly handle unsupported versions.  Some version numbers
#    (0x?a?a?a?a, as defined in Section 15) are reserved for inclusion in
#    fields that contain version numbers.
# 
#    Endpoints MAY add reserved versions to any field where unknown or
#    unsupported versions are ignored to test that a peer correctly
#    ignores the value.  For instance, an endpoint could include a
#    reserved version in a Version Negotiation packet; see Section 17.2.1.
#    Endpoints MAY send packets with a reserved version to test that a
#    peer correctly discards the packet.

[[spec]]
level = "MAY"
quote = '''
Endpoints MAY add reserved versions to any field where unknown or
unsupported versions are ignored to test that a peer correctly
ignores the value.
'''

[[spec]]
level = "MAY"
quote = '''
Endpoints MAY send packets with a reserved version to test that a
peer correctly discards the packet.
'''

