target = "https://www.rfc-editor.org/rfc/rfc9000#section-8.2.3"

# Successful Path Validation
#
#    Path validation succeeds when a PATH_RESPONSE frame is received that
#    contains the data that was sent in a previous PATH_CHALLENGE frame.
#    A PATH_RESPONSE frame received on any network path validates the path
#    on which the PATH_CHALLENGE was sent.
# 
#    If an endpoint sends a PATH_CHALLENGE frame in a datagram that is not
#    expanded to at least 1200 bytes and if the response to it validates
#    the peer address, the path is validated but not the path MTU.  As a
#    result, the endpoint can now send more than three times the amount of
#    data that has been received.  However, the endpoint MUST initiate
#    another path validation with an expanded datagram to verify that the
#    path supports the required MTU.
# 
#    Receipt of an acknowledgment for a packet containing a PATH_CHALLENGE
#    frame is not adequate validation, since the acknowledgment can be
#    spoofed by a malicious peer.

[[spec]]
level = "MUST"
quote = '''
However, the endpoint MUST initiate
another path validation with an expanded datagram to verify that the
path supports the required MTU.
'''

