target = "https://www.rfc-editor.org/rfc/rfc9001#section-5.1"

[[exception]]
quote = '''
Other versions of TLS MUST
provide a similar function in order to be used with QUIC.
'''
reason = '''
TLS support is implemented through a provider and is unenforceable by
s2n-quic.
'''

