target = "https://www.rfc-editor.org/rfc/rfc9001#section-5.2"

[[exception]]
quote = '''
Future versions of QUIC SHOULD generate a new salt value, thus
ensuring that the keys are different for each version of QUIC.
'''
reason = '''
This only applies to future definitions of QUIC, not implementations.
'''

[[exception]]
quote = '''
The HKDF-Expand-Label function defined in TLS 1.3 MUST be used for
Initial packets even where the TLS versions offered do not include
TLS 1.3.
'''
reason = '''
s2n-quic only offers TLS 1.3
'''

