target = "https://www.rfc-editor.org/rfc/rfc9001#section-8.1"

[[exception]]
quote = '''
An application protocol MAY restrict the QUIC versions that it can
operate over.
'''
reason = '''
s2n-quic does not define any application protocols so this does not apply
'''

