target = "https://www.rfc-editor.org/rfc/rfc9001#section-8.4"

[[exception]]
quote = '''
A client MUST NOT request the use of the
TLS 1.3 compatibility mode.
'''
reason = '''
TLS support is implemented through a provider and is unenforceable by
s2n-quic.
'''

[[exception]]
quote = '''
A server SHOULD treat the receipt of a
TLS ClientHello with a non-empty legacy_session_id field as a
connection error of type PROTOCOL_VIOLATION.
'''
reason = '''
TLS support is implemented through a provider and is unenforceable by
s2n-quic.
'''
