# https://tools.ietf.org/id/draft-ietf-quic-tls-32.txt#4.8
#
# 4.8.  TLS Errors
#
# If TLS experiences an error, it generates an appropriate alert as
# defined in Section 6 of [TLS13].
# 
# A TLS alert is converted into a QUIC connection error.  The alert
# description is added to 0x100 to produce a QUIC error code from the
# range reserved for CRYPTO_ERROR.  The resulting value is sent in a
# QUIC CONNECTION_CLOSE frame of type 0x1c.
# 
# The alert level of all TLS alerts is "fatal"; a TLS stack MUST NOT
# generate alerts at the "warning" level.
# 
# QUIC permits the use of a generic code in place of a specific error
# code; see Section 11 of [QUIC-TRANSPORT].  For TLS alerts, this
# includes replacing any alert with a generic alert, such as
# handshake_failure (0x128 in QUIC).  Endpoints MAY use a generic error
# code to avoid possibly exposing confidential information.

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-tls-32.txt#4.8"
level = "MUST"
quote = '''
The alert level of all TLS alerts is "fatal"; a TLS stack MUST NOT
generate alerts at the "warning" level.
'''

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-tls-32.txt#4.8"
level = "MAY"
quote = '''
Endpoints MAY use a generic error
code to avoid possibly exposing confidential information.
'''

