[toolchain]
# pin the version to prevent random breakage
channel = "nightly-2025-03-31"
# The source code of rustc, provided by the rust-src component, is needed for
# building eBPF programs.
components = [ "rustc", "cargo", "rust-src" ]
