# https://tools.ietf.org/id/draft-ietf-quic-recovery-32.txt#6.4
#
# 6.4.  Discarding Keys and Packet State
#
# When packet protection keys are discarded (see Section 4.9 of
# [QUIC-TLS]), all packets that were sent with those keys can no longer
# be acknowledged because their acknowledgements cannot be processed
# anymore.  The sender MUST discard all recovery state associated with
# those packets and MUST remove them from the count of bytes in flight.
# 
# Endpoints stop sending and receiving Initial packets once they start
# exchanging Handshake packets; see Section 17.2.2.1 of
# [QUIC-TRANSPORT].  At this point, recovery state for all in-flight
# Initial packets is discarded.
# 
# When 0-RTT is rejected, recovery state for all in-flight 0-RTT
# packets is discarded.
# 
# If a server accepts 0-RTT, but does not buffer 0-RTT packets that
# arrive before Initial packets, early 0-RTT packets will be declared
# lost, but that is expected to be infrequent.
# 
# It is expected that keys are discarded after packets encrypted with
# them would be acknowledged or declared lost.  However, Initial
# secrets are discarded as soon as handshake keys are proven to be
# available to both client and server; see Section 4.9.1 of [QUIC-TLS].

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-recovery-32.txt#6.4"
level = "MUST"
quote = '''
The sender MUST discard all recovery state associated with
those packets and MUST remove them from the count of bytes in flight.
'''

[[spec]]
target = "https://tools.ietf.org/id/draft-ietf-quic-recovery-32.txt#6.4"
level = "MUST"
quote = '''
The sender MUST discard all recovery state associated with
those packets and MUST remove them from the count of bytes in flight.
'''

