[package]
name = "echo"
version = "0.1.0"
authors = ["Cameron Bytheway <bythewc@amazon.com>"]
edition = "2018"

[dependencies]
s2n-quic = { version = "0.1", path = "../../quic/s2n-quic" }
tokio = { version = "1", features = ["full"] }

[workspace]
members = ["."]
