target = "https://www.rfc-editor.org/rfc/rfc8899#section-5"

# Datagram Packetization Layer PMTUD
#
#    This section specifies Datagram PLPMTUD (DPLPMTUD).  The method can
#    be introduced at various points (as indicated with * in Figure 2) in
#    the IP protocol stack to discover the PLPMTU so that an application
#    can utilize an appropriate MPS for the current network path.
# 
#    DPLPMTUD SHOULD only be performed at one layer between a pair of
#    endpoints.  Therefore, an upper PL or application should avoid using
#    DPLPMTUD when this is already enabled in a lower layer.  A PL MUST
#    adjust the MPS indicated by DPLPMTUD to account for any additional
#    overhead introduced by the PL.
# 
#    +----------------------+
#    |     Application*     |
#    +-----+------------+---+
#          |            |
#      +---+--+      +--+--+
#      | QUIC*|      |SCTP*|
#      +---+--+      +-+-+-+
#          |           | |
#          +---+  +----+ |
#              |  |      |
#            +-+--+-+    |
#            | UDP  |    |
#            +---+--+    |
#                |       |
#    +-----------+-------+--+
#    |  Network Interface   |
#    +----------------------+
# 
#             Figure 2: Examples Where DPLPMTUD Can Be Implemented
# 
#    The central idea of DPLPMTUD is probing by a sender.  Probe packets
#    are sent to find the maximum size of user message that can be
#    completely transferred across the network path from the sender to the
#    destination.
# 
#    The following sections identify the components needed for
#    implementation, provide an overview of the phases of operation, and
#    specify the state machine and search algorithm.

[[spec]]
level = "SHOULD"
quote = '''
DPLPMTUD SHOULD only be performed at one layer between a pair of
endpoints.
'''

[[spec]]
level = "MUST"
quote = '''
A PL MUST
adjust the MPS indicated by DPLPMTUD to account for any additional
overhead introduced by the PL.
'''

