target = "https://www.rfc-editor.org/rfc/rfc8899#section-2"

# Terminology
#
#    The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
#    "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and
#    "OPTIONAL" in this document are to be interpreted as described in
#    BCP 14 [RFC2119] [RFC8174] when, and only when, they appear in all
#    capitals, as shown here.
# 
#    The following terminology is defined.  Relevant terms are directly
#    copied from [RFC4821], and the definitions in [RFC1122] apply.
# 
#    Acknowledged PL:  A PL that includes a mechanism that can confirm
#       successful delivery of datagrams to the remote PL endpoint (e.g.,
#       SCTP).  Typically, the PL receiver returns acknowledgments
#       corresponding to the received datagrams, which can be utilized to
#       detect black-holing of packets (c.f., Unacknowledged PL).
# 
#    Actual PMTU:  The actual PMTU is the PMTU of a network path between a
#       sender PL and a destination PL, which the DPLPMTUD algorithm seeks
#       to determine.
# 
#    Black Hole:  A black hole is encountered when a sender is unaware
#       that packets are not being delivered to the destination endpoint.
#       Two types of black hole are relevant to DPLPMTUD:
# 
#       *  Packets encounter a packet black hole when packets are not
#          delivered to the destination endpoint (e.g., when the sender
#          transmits packets of a particular size with a previously known
#          effective PMTU, and they are discarded by the network).
# 
#       *  An ICMP black hole is encountered when the sender is unaware
#          that packets are not delivered to the destination endpoint
#          because PTB messages are not received by the originating PL
#          sender.
# 
#    Classical Path MTU Discovery:  Classical PMTUD is a process described
#       in [RFC1191] and [RFC8201] in which nodes rely on PTB messages to
#       learn the largest size of unfragmented packet that can be used
#       across a network path.
# 
#    Datagram:  A datagram is a transport-layer protocol data unit,
#       transmitted in the payload of an IP packet.
# 
#    DPLPMTUD:  Datagram Packetization Layer Path MTU Discovery
#       (DPLPMTUD), PLPMTUD performed using a datagram transport protocol.
# 
#    Effective PMTU:  The effective PMTU is the current estimated value
#       for PMTU that is used by a PMTUD.  This is equivalent to the
#       PLPMTU derived by PLPMTUD plus the size of any headers added below
#       the PL, including the IP layer headers.
# 
#    EMTU_S:  The effective MTU for sending (EMTU_S) is defined in
#       [RFC1122] as "the maximum IP datagram size that may be sent, for a
#       particular combination of IP source and destination addresses...".
# 
#    EMTU_R:  The effective MTU for receiving (EMTU_R) is designated in
#       [RFC1122] as "the largest datagram size that can be reassembled".
# 
#    Link:  A link is a communication facility or medium over which nodes
#       can communicate at the link layer, i.e., a layer below the IP
#       layer.  Examples are Ethernet LANs and Internet (or higher) layer
#       tunnels.
# 
#    Link MTU:  The link Maximum Transmission Unit (MTU) is the size in
#       bytes of the largest IP packet, including the IP header and
#       payload, that can be transmitted over a link.  Note that this
#       could more properly be called the IP MTU, to be consistent with
#       how other standards organizations use the acronym.  This includes
#       the IP header but excludes link layer headers and other framing
#       that is not part of IP or the IP payload.  Other standards
#       organizations generally define the link MTU to include the link
#       layer headers.  This specification continues the requirement in
#       [RFC4821] that states, "All links MUST enforce their MTU: links
#       that might non-deterministically deliver packets that are larger
#       than their rated MTU MUST consistently discard such packets."
# 
#    MAX_PLPMTU:  The MAX_PLPMTU is the largest size of PLPMTU that
#       DPLPMTUD will attempt to use (see the constants defined in
#       Section 5.1.2).
# 
#    MIN_PLPMTU:  The MIN_PLPMTU is the smallest size of PLPMTU that
#       DPLPMTUD will attempt to use (see the constants defined in
#       Section 5.1.2).
# 
#    MPS:  The Maximum Packet Size (MPS) is the largest size of
#       application data block that can be sent across a network path by a
#       PL using a single datagram (see Section 4.4).
# 
#    MSL:  The Maximum Segment Lifetime (MSL) is the maximum delay a
#       packet is expected to experience across a path, taken as 2 minutes
#       [BCP145].
# 
#    Packet:  A packet is the IP header(s) and any extension headers/
#       options plus the IP payload.
# 
#    Packetization Layer (PL):  The PL is a layer of the network stack
#       that places data into packets and performs transport protocol
#       functions.  Examples of a PL include TCP, SCTP, SCTP over UDP,
#       SCTP over DTLS, or QUIC.
# 
#    Path:  The path is the set of links and routers traversed by a packet
#       between a source node and a destination node by a particular flow.
# 
#    Path MTU (PMTU):  The Path MTU (PMTU) is the minimum of the link MTU
#       of all the links forming a network path between a source node and
#       a destination node, as used by PMTUD.
# 
#    PTB:  In this document, the term PTB message is applied to both IPv4
#       ICMP Unreachable messages (Type 3) that carry the error
#       Fragmentation Needed (Type 3, Code 4) [RFC0792] and ICMPv6 Packet
#       Too Big messages (Type 2) [RFC4443].
# 
#    PTB_SIZE:  The PTB_SIZE is a value reported in a validated PTB
#       message that indicates next-hop link MTU of a router along the
#       path.
# 
#    PL_PTB_SIZE:  The size reported in a validated PTB message, reduced
#       by the size of all headers added by layers below the PL.
# 
#    PLPMTU:  The Packetization Layer PMTU is an estimate of the largest
#       size of PL datagram that can be sent by a path, controlled by
#       PLPMTUD.
# 
#    PLPMTUD:  Packetization Layer Path MTU Discovery (PLPMTUD), the
#       method described in this document for datagram PLs, which is an
#       extension to Classical PMTU Discovery.
# 
#    Probe packet:  A probe packet is a datagram sent with a purposely
#       chosen size (typically the current PLPMTU or larger) to detect if
#       packets of this size can be successfully sent end-to-end across
#       the network path.
# 
#    Unacknowledged PL:  A PL that does not itself provide a mechanism to
#       confirm delivery of datagrams to the remote PL endpoint (e.g.,
#       UDP), and therefore requires DPLPMTUD to provide a mechanism to
#       detect black-holing of packets (c.f., Acknowledged PL).

[[spec]]
level = "MUST"
quote = '''
This specification continues the requirement in
[RFC4821] that states, "All links MUST enforce their MTU: links
that might non-deterministically deliver packets that are larger
than their rated MTU MUST consistently discard such packets."
'''

[[spec]]
level = "MUST"
quote = '''
This specification continues the requirement in
[RFC4821] that states, "All links MUST enforce their MTU: links
that might non-deterministically deliver packets that are larger
than their rated MTU MUST consistently discard such packets."
'''

