target = "https://www.rfc-editor.org/rfc/rfc8899#section-6.2.1.4"

# PTB Message Handling by SCTP
#
#    Normal ICMP validation MUST be performed as specified in Appendix C
#    of [RFC4960].  This requires that the first 8 bytes of the SCTP
#    common header are quoted in the payload of the PTB message, which can
#    be the case for ICMPv4 and is normally the case for ICMPv6.
# 
#    When a PTB message has been validated, the PL_PTB_SIZE calculated
#    from the PTB_SIZE reported in the PTB message SHOULD be used with the
#    DPLPMTUD algorithm, provided that the reported PL_PTB_SIZE is less
#    than the current probe size (see Section 4.6).

[[spec]]
level = "MUST"
quote = '''
Normal ICMP validation MUST be performed as specified in Appendix C
of [RFC4960].
'''

[[spec]]
level = "SHOULD"
quote = '''
When a PTB message has been validated, the PL_PTB_SIZE calculated
from the PTB_SIZE reported in the PTB message SHOULD be used with the
DPLPMTUD algorithm, provided that the reported PL_PTB_SIZE is less
than the current probe size (see Section 4.6).
'''

