target = "https://www.rfc-editor.org/rfc/rfc8899#section-6.2.1.3"

# Validating the Path with SCTP
#
#    Since SCTP provides an acknowledged PL, a sender MUST NOT implement
#    the CONFIRMATION_TIMER while in the SEARCH_COMPLETE state.

[[spec]]
level = "MUST"
quote = '''
Since SCTP provides an acknowledged PL, a sender MUST NOT implement
the CONFIRMATION_TIMER while in the SEARCH_COMPLETE state.
'''

