target = "https://www.rfc-editor.org/rfc/rfc8899#section-6.1"

# Application Support for DPLPMTUD with UDP or UDP-Lite
#
#    The current specifications of UDP [RFC0768] and UDP-Lite [RFC3828] do
#    not define a method in the RFC series that supports PLPMTUD.  In
#    particular, the UDP transport does not provide the transport features
#    needed to implement datagram PLPMTUD.
# 
#    The DPLPMTUD method can be implemented as a part of an application
#    built directly or indirectly on UDP or UDP-Lite but relies on higher-
#    layer protocol features to implement the method [BCP145].
# 
#    Some primitives used by DPLPMTUD might not be available via the
#    Datagram API (e.g., the ability to access the PLPMTU from the IP-
#    layer cache or to interpret received PTB messages).
# 
#    In addition, it is recommended that PMTU discovery is not performed
#    by multiple protocol layers.  An application SHOULD avoid using
#    DPLPMTUD when the underlying transport system provides this
#    capability.  A common method for managing the PLPMTU has benefits,
#    both in the ability to share state between different processes and in
#    opportunities to coordinate probing for different PL instances.

[[spec]]
level = "SHOULD"
quote = '''
An application SHOULD avoid using
DPLPMTUD when the underlying transport system provides this
capability.
'''

