target = "https://www.rfc-editor.org/rfc/rfc8899#section-6.2.2.4"

# Handling of PTB Messages by SCTP/UDP
#
#    ICMP validation MUST be performed for PTB messages as specified in
#    Appendix C of [RFC4960].  This requires that the first 8 bytes of the
#    SCTP common header are contained in the PTB message, which can be the
#    case for ICMPv4 (but note the UDP header also consumes a part of the
#    quoted packet header) and is normally the case for ICMPv6.  When the
#    validation is completed, the PL_PTB_SIZE calculated from the PTB_SIZE
#    in the PTB message SHOULD be used with the DPLPMTUD providing that
#    the reported PL_PTB_SIZE is less than the current probe size.

[[spec]]
level = "MUST"
quote = '''
ICMP validation MUST be performed for PTB messages as specified in
Appendix C of [RFC4960].
'''

[[spec]]
level = "SHOULD"
quote = '''
When the
validation is completed, the PL_PTB_SIZE calculated from the PTB_SIZE
in the PTB message SHOULD be used with the DPLPMTUD providing that
the reported PL_PTB_SIZE is less than the current probe size.
'''

