target = "https://www.rfc-editor.org/rfc/rfc8899#section-6.1.6"

# Handling of PTB Messages
#
#    An application that is able and wishes to receive PTB messages MUST
#    perform ICMP validation as specified in Section 5.2 of [BCP145].
#    This requires that the application checks each received PTB message
#    to validate that it was is received in response to transmitted
#    traffic and that the reported PL_PTB_SIZE is less than the current
#    probed size (see Section 4.6.2).  A validated PTB message MAY be used
#    as input to the DPLPMTUD algorithm but MUST NOT be used directly to
#    set the PLPMTU.

[[spec]]
level = "MUST"
quote = '''
An application that is able and wishes to receive PTB messages MUST
perform ICMP validation as specified in Section 5.2 of [BCP145].
'''

[[spec]]
level = "MUST"
quote = '''
A validated PTB message MAY be used
as input to the DPLPMTUD algorithm but MUST NOT be used directly to
set the PLPMTU.
'''

