target = "https://www.rfc-editor.org/rfc/rfc8899#section-4.5"

# Disabling the Effect of PMTUD
#
#    A PL implementing this specification MUST suspend network layer
#    processing of outgoing packets that enforces a PMTU
#    [RFC1191][RFC8201] for each flow utilizing DPLPMTUD and instead use
#    DPLPMTUD to control the size of packets that are sent by a flow.
#    This removes the need for the network layer to drop or to fragment
#    sent packets that have a size greater than the PMTU.

[[spec]]
level = "MUST"
quote = '''
A PL implementing this specification MUST suspend network layer
processing of outgoing packets that enforces a PMTU
[RFC1191][RFC8201] for each flow utilizing DPLPMTUD and instead use
DPLPMTUD to control the size of packets that are sent by a flow.
'''

