target = "https://www.rfc-editor.org/rfc/rfc8899#section-5.3.2"

# Selection of Probe Sizes
#
#    The search algorithm determines a minimum useful gain in PLPMTU.  It
#    would not be constructive for a PL sender to attempt to probe for all
#    sizes.  This would incur unnecessary load on the path.
#    Implementations SHOULD select the set of probe packet sizes to
#    maximize the gain in PLPMTU from each search step.
# 
#    Implementations could optimize the search procedure by selecting step
#    sizes from a table of common PMTU sizes.  When selecting the
#    appropriate next size to search, an implementer ought to also
#    consider that there can be common sizes of MPS that applications seek
#    to use, and there could be common sizes of MTU used within the
#    network.

[[spec]]
level = "SHOULD"
quote = '''
Implementations SHOULD select the set of probe packet sizes to
maximize the gain in PLPMTU from each search step.
'''

