target = "https://www.rfc-editor.org/rfc/rfc8899#section-5.1.2"

# Constants
#
#    The following constants are defined:
# 
#    MAX_PROBES:  The MAX_PROBES is the maximum value of the PROBE_COUNT
#       counter (see Section 5.1.3).  MAX_PROBES represents the limit for
#       the number of consecutive probe attempts of any size.  Search
#       algorithms benefit from a MAX_PROBES value greater than 1 because
#       this can provide robustness to isolated packet loss.  The default
#       value of MAX_PROBES is 3.
# 
#    MIN_PLPMTU:  The MIN_PLPMTU is the smallest size of PLPMTU that
#       DPLPMTUD will attempt to use.  An endpoint could need to configure
#       the MIN_PLPMTU to provide space for extension headers and other
#       encapsulations at layers below the PL.  This value can be
#       interface and path dependent.  For IPv6, this size is greater than
#       or equal to the size at the PL that results in an 1280-byte IPv6
#       packet, as specified in [RFC8200].  For IPv4, this size is greater
#       than or equal to the size at the PL that results in an 68-byte
#       IPv4 packet.  Note: An IPv4 router is required to be able to
#       forward a datagram of 68 bytes without further fragmentation.
#       This is the combined size of an IPv4 header and the minimum
#       fragment size of 8 bytes.  In addition, receivers are required to
#       be able to reassemble fragmented datagrams at least up to 576
#       bytes, as stated in Section 3.3.3 of [RFC1122].
# 
#    MAX_PLPMTU:  The MAX_PLPMTU is the largest size of PLPMTU.  This has
#       to be less than or equal to the maximum size of the PL packet that
#       can be sent on the outgoing interface (constrained by the local
#       interface MTU).  When known, this also ought to be less than the
#       maximum size of PL packet that can be received by the remote
#       endpoint (constrained by EMTU_R).  It can be limited by the design
#       or configuration of the PL being used.  An application, or PL, MAY
#       choose a smaller MAX_PLPMTU when there is no need to send packets
#       larger than a specific size.
# 
#    BASE_PLPMTU:  The BASE_PLPMTU is a configured size expected to work
#       for most paths.  The size is equal to or larger than the
#       MIN_PLPMTU and smaller than the MAX_PLPMTU.  For most PLs, a
#       suitable BASE_PLPMTU will be larger than 1200 bytes.  When using
#       IPv4, there is no currently equivalent size specified, and a
#       default BASE_PLPMTU of 1200 bytes is RECOMMENDED.

[[spec]]
level = "MAY"
quote = '''
An application, or PL, MAY
choose a smaller MAX_PLPMTU when there is no need to send packets
larger than a specific size.
'''

[[spec]]
level = "SHOULD"
quote = '''
When using
IPv4, there is no currently equivalent size specified, and a
default BASE_PLPMTU of 1200 bytes is RECOMMENDED.
'''

