[workspace]
members = ["s2n-quic-xdp", "tester", "xtask"]
resolver = "2"

[workspace.dependencies]
aya-obj = "=0.2.1" # new version requires MSRV 1.87.0 https://crates.io/crates/aya-obj/versions
bolero = "0.13"
bolero-generator = { version = "0.13", default-features = false }
