[workspace]
members = ["s2n-quic-xdp", "tester", "xtask"]
resolver = "2"

[workspace.dependencies]
aya = "=0.13.1" # new version requires MSRV 1.87.0
aya-log = "=0.2.0" # new version requires MSRV 1.87.0
aya-log-common = "=0.1.14" # new version requires MSRV 1.87.0
bolero = "0.13"
bolero-generator = { version = "0.13", default-features = false }
