target = "https://www.rfc-editor.org/rfc/rfc9002#section-6.2.2"

[[TODO]]
quote = '''
Resumed connections over the same network MAY use the previous
connection's final smoothed RTT value as the resumed connection's
initial RTT.
'''
feature = "Resumed connection RTT"
tracking-issue = "144"
