[[TODO]]
target = "https://www.rfc-editor.org/rfc/rfc9000#section-8.2.1"
tracking-issue = "409"
feature = "Connection migration"
quote = '''
An endpoint MAY send multiple PATH_CHALLENGE frames to guard against
packet loss.
'''

[[TODO]]
target = "https://www.rfc-editor.org/rfc/rfc9000#section-8.2.1"
tracking-issue = "409"
feature = "Connection migration"
quote = '''
However, an endpoint SHOULD NOT send multiple
PATH_CHALLENGE frames in a single packet.
'''

[[TODO]]
target = "https://www.rfc-editor.org/rfc/rfc9000#section-8.2.1"
tracking-issue = "410"
feature = "Connection migration"
quote = '''
An endpoint MUST expand datagrams that contain a PATH_CHALLENGE frame
to at least the smallest allowed maximum datagram size of 1200 bytes.
'''

[[TODO]]
target = "https://www.rfc-editor.org/rfc/rfc9000#section-8.2.2"
tracking-issue = "410"
feature = "Client connection migration"
quote = '''
An endpoint MUST expand datagrams that contain a PATH_RESPONSE frame
to at least the smallest allowed maximum datagram size of 1200 bytes.
'''

[[TODO]]
target = "https://www.rfc-editor.org/rfc/rfc9000#section-8.2.1"
tracking-issue = "411"
feature = "Connection migration"
quote = '''
An endpoint SHOULD NOT probe a new path with packets containing a
PATH_CHALLENGE frame more frequently than it would send an Initial
packet.
'''

[[TODO]]
target = "https://www.rfc-editor.org/rfc/rfc9000#section-8.2.2"
tracking-issue = "405"
feature = "Connection migration"
quote = '''
A PATH_RESPONSE frame MUST be sent on the network path where the
PATH_CHALLENGE frame was received.
'''

[[TODO]]
target = "https://www.rfc-editor.org/rfc/rfc9000#section-8.2.2"
tracking-issue = "405"
feature = "Connection migration"
quote = '''
This requirement MUST NOT be enforced by the endpoint that initiates
path validation, as that would enable an attack on migration; see
Section 9.3.3.
'''

[[TODO]]
target = "https://www.rfc-editor.org/rfc/rfc9000#section-8.2"
tracking-issue = "414"
feature = "Connection migration"
quote = '''
An endpoint MAY include other frames with the PATH_CHALLENGE and
PATH_RESPONSE frames used for path validation.
'''

