[package]
name = "udp-attack"
version = "0.1.0"
edition = "2021"
publish = false
rust-version = "1.84"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
rand = "0.8"

[workspace]
members = ["."]
