target = "https://www.rfc-editor.org/rfc/rfc9001#section-4.6.2"

[[TODO]]
quote = '''
When rejecting 0-RTT, a server MUST NOT
process any 0-RTT packets, even if it could.
'''
feature = "0-RTT"

[[TODO]]
quote = '''
When 0-RTT was
rejected, a client SHOULD treat receipt of an acknowledgement for a
0-RTT packet as a connection error of type PROTOCOL_VIOLATION, if it
is able to detect the condition.
'''
feature = "0-RTT"

[[TODO]]
quote = '''
The client therefore MUST reset the state of all
streams, including application state bound to those streams.
'''
feature = "0-RTT"

[[TODO]]
quote = '''
A client MAY reattempt 0-RTT if it receives a Retry or Version
Negotiation packet.
'''
feature = "0-RTT"

