target = "https://www.rfc-editor.org/rfc/rfc9001#section-5.3"

[[TODO]]
quote = '''
An endpoint MUST initiate a key update
(Section 6) prior to exceeding any limit set for the AEAD that is in
use.
'''
tracking-issue = "318"
feature = "Key update"
