target = "https://www.rfc-editor.org/rfc/rfc9001#section-6.2"

[[TODO]]
quote = '''
An endpoint that receives an acknowledgement that is carried in a
packet protected with old keys where any acknowledged packet was
protected with newer keys MAY treat that as a connection error of
type KEY_UPDATE_ERROR.
'''
tracking-issue = "479"
feature = "Key update"
