target = "https://www.rfc-editor.org/rfc/rfc9001#section-9.2"

[[TODO]]
quote = '''
Endpoints MUST implement and use the replay protections described in
[TLS13], however it is recognized that these protections are
imperfect.
'''
tracking-issue = "327"
feature = "0-RTT"

[[TODO]]
quote = '''
An application
protocol that uses QUIC MUST describe how the protocol uses 0-RTT and
the measures that are employed to protect against replay attack.
'''
tracking-issue = "327"
feature = "0-RTT"
